### PR TITLE
Added login and signup page

### PR DESCRIPTION
**Pull request by RohitLakra299**
Added signup and login page
issue #3

### CODE REVIEW

**Review by Rohit-554 — COMMENTED** [review]
Add hactoberfest or hacktoberfest 2022 tag in your pr

**Comment by Rohit-554** [comment]
Thanks for Your Contribution

**Comment by Rohit-554** [comment]
Can you again create a pull request, Something went wrong

**Comment by Rohit-554** [comment]
Can you again create a pull request, Something went wrong

**Comment by Rohit-554** [comment]
> Added signup and login page issue #3

Can you again create a pull request, Something went wrong

**Comment by RohitLakra299** [comment]
@Rohit-554 should I again create a pull request?

**Comment by Rohit-554** [comment]
Yes

**Pull request merged**
